_wandb:
    value:
        cli_version: 0.21.4
        e:
            jtegrss5rfgkcwdilyzx4wxi2y5ft06v:
                args:
                    - --policy.type=act
                    - --dataset.repo_id=lt-s/AMD_hackathon_drape_blanket
                    - --policy.output_features={"action":{"type":"ACTION","shape":[12]}}
                    - --policy.input_features={"observation.state":{"type":"STATE","shape":[12]}, "observation.images.front":{"type":"VISUAL","shape":[3,256,256]}, "observation.images.above":{"type":"VISUAL","shape":[3,256,256]}}
                    - --policy.normalization_mapping={"VISUAL":"IDENTITY","STATE":"MEAN_STD","ACTION":"MEAN_STD"}
                    - --policy.optimizer_lr=1e-4
                    - --policy.optimizer_weight_decay=0.01
                    - --batch_size=64
                    - --steps=6000
                    - --save_freq=1000
                    - --log_freq=100
                    - --policy.device=cuda
                    - --output_dir=outputs/train/mission2_act_003
                    - --job_name=mission2_act_003
                    - --wandb.enable=true
                    - --tensorboard.enable=true
                    - --dataset.video_backend=pyav
                    - --policy.push_to_hub=false
                cpu_count: 160
                cpu_count_logical: 160
                disk:
                    /:
                        total: "2162185003008"
                        used: "1124043878400"
                executable: /root/miniconda3/envs/lerobot-pi05/bin/python3.10
                gpu: AMD Instinct MI300X VF
                gpu_amd:
                    - id: "0"
                      maxPower: "750.0"
                      mclkRange: 900Mhz - 1300Mhz
                      model: "0x74b5"
                      performanceLevel: auto
                      sclkRange: 500Mhz - 2100Mhz
                      series: AMD Instinct MI300X VF
                      sku: M3000100
                      uniqueId: "0x257b923d7129db22"
                      vbiosVersion: 113-M3000100-103
                      vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                gpu_count: 1
                host: robotics-jupyter-launcher-3958
                memory:
                    total: "2029207171072"
                os: Linux-6.1.0-39-amd64-x86_64-with-glibc2.39
                program: /root/miniconda3/envs/lerobot-pi05/bin/lerobot-train
                python: CPython 3.10.19
                root: outputs/train/mission2_act_003
                startedAt: "2025-12-06T22:49:04.495046Z"
                writerId: jtegrss5rfgkcwdilyzx4wxi2y5ft06v
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.19
            "5": 0.21.4
            "6": 4.53.3
            "10":
                - 21
            "12": 0.21.4
            "13": linux-x86_64
batch_size:
    value: 64
checkpoint_path:
    value: null
dataset:
    value:
        episodes: null
        image_transforms:
            enable: false
            max_num_transforms: 3
            random_order: false
            tfs:
                affine:
                    kwargs:
                        degrees:
                            - -5
                            - 5
                        translate:
                            - 0.05
                            - 0.05
                    type: RandomAffine
                    weight: 1
                brightness:
                    kwargs:
                        brightness:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                contrast:
                    kwargs:
                        contrast:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                hue:
                    kwargs:
                        hue:
                            - -0.05
                            - 0.05
                    type: ColorJitter
                    weight: 1
                saturation:
                    kwargs:
                        saturation:
                            - 0.5
                            - 1.5
                    type: ColorJitter
                    weight: 1
                sharpness:
                    kwargs:
                        sharpness:
                            - 0.5
                            - 1.5
                    type: SharpnessJitter
                    weight: 1
        repo_id: lt-s/AMD_hackathon_drape_blanket
        revision: null
        root: null
        streaming: false
        use_imagenet_stats: true
        video_backend: pyav
env:
    value: null
eval:
    value:
        batch_size: 50
        n_episodes: 50
        use_async_envs: false
eval_freq:
    value: 20000
job_name:
    value: mission2_act_003
log_freq:
    value: 100
num_workers:
    value: 4
optimizer:
    value:
        betas:
            - 0.9
            - 0.999
        eps: 1e-08
        grad_clip_norm: 10
        lr: 0.0001
        type: adamw
        weight_decay: 0.01
output_dir:
    value: outputs/train/mission2_act_003
policy:
    value:
        chunk_size: 100
        device: cuda
        dim_feedforward: 3200
        dim_model: 512
        dropout: 0.1
        feedforward_activation: relu
        input_features:
            observation.images.above:
                shape:
                    - 3
                    - 256
                    - 256
                type: VISUAL
            observation.images.front:
                shape:
                    - 3
                    - 256
                    - 256
                type: VISUAL
            observation.state:
                shape:
                    - 12
                type: STATE
        kl_weight: 10
        latent_dim: 32
        license: null
        n_action_steps: 100
        n_decoder_layers: 1
        n_encoder_layers: 4
        n_heads: 8
        n_obs_steps: 1
        n_vae_encoder_layers: 4
        normalization_mapping:
            ACTION: MEAN_STD
            STATE: MEAN_STD
            VISUAL: IDENTITY
        optimizer_lr: 0.0001
        optimizer_lr_backbone: 1e-05
        optimizer_weight_decay: 0.01
        output_features:
            action:
                shape:
                    - 12
                type: ACTION
        pre_norm: false
        pretrained_backbone_weights: ResNet18_Weights.IMAGENET1K_V1
        pretrained_path: null
        private: null
        push_to_hub: false
        replace_final_stride_with_dilation: false
        repo_id: null
        tags: null
        temporal_ensemble_coeff: null
        type: act
        use_amp: false
        use_vae: true
        vision_backbone: resnet18
resume:
    value: false
save_checkpoint:
    value: true
save_freq:
    value: 1000
scheduler:
    value: null
seed:
    value: 1000
steps:
    value: 6000
tensorboard:
    value:
        enable: true
        log_dir: null
use_policy_training_preset:
    value: true
wandb:
    value:
        disable_artifact: false
        enable: true
        entity: null
        mode: null
        notes: null
        project: lerobot
        run_id: null
